import { Inter } from 'next/font/google'
import '../globals.css'
import Sidebar from '@/components/Sidebar';
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { Page } from "@/models/Page";
import mongoose from "mongoose";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);
  mongoose.connect(process.env.MONGODB_URI);

  const page = await Page.findOne({owner: session?.user?.email});

  return (
    <html lang="en">
      <body className={inter.className} id='app'>
        <main className='flex min-h-screen md:max-w-6xl m-auto'>
          <Sidebar page={JSON.parse(JSON.stringify(page))} session={JSON.parse(JSON.stringify(session))}/>
          <div className='grow p-4'>
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}